channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - sphinx==4.0.2
  - myst-parser==0.15.1
  - pip==21.2.*
#  - nbsphinx==0.8.1
  - pip:
    - sphinx_rtd_theme==0.5.2
    - sphinx-comments==0.0.3